version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: nestjs-tesla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123#
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Uncomment below if you want to load an init script
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
